/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary": "#6b3700",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "surface": "#f8f9ff",
        "secondary": "#565e74",
        "on-primary": "#ffffff",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#ffb77d",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#b7c4ff",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#cad3ff",
        "on-tertiary-container": "#ffcba3",
        "on-surface": "#0b1c30",
        "on-error": "#ffffff",
        "primary-container": "#1d4ed8",
        "tertiary-fixed": "#ffdcc3",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#131b2e",
        "surface-tint": "#2151da",
        "on-primary-fixed-variant": "#0039b5",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#dce1ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b7c4ff",
        "secondary-fixed": "#dae2fd",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed": "#2f1500",
        "on-background": "#0b1c30",
        "outline-variant": "#c4c5d7",
        "outline": "#747686",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#434655",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "primary": "#0037b0",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed": "#001551",
        "tertiary-container": "#8d4b00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
        "space-xl": "2.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "label-lg": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-sm": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "label-sm": ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-lg": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-xl-mobile": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
